version: "3"
services:
  django:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: "gymkhana-sac-backend:latest"
    container_name: django
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=postgresql
    ports:
      - 9999:9999
    volumes:
      - ./backend:/app
    depends_on:
      - postgresql
    networks:
      - app-network
    command:
      - /bin/sh
      - -c
      - |
        python manage.py flush --no-input
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
  dbpostgresql:
    image: "bitnami/postgresql:latest"
    container_name: postgresql
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRESQL_USERNAME=$DB_USER
      - POSTGRESQL_PASSWORD=$DB_PASSWORD
      - POSTGRESQL_DATABASE=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/bitnami/postgresql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
